support GHC 9.4 (Word# -> Word64#)
fumieval/word-compat pull request #7
Opened 2022-08-26 12:43 UTC by raehik

GHC 9.4 switches `Word64` internal representation to `Word64#` from
`Word#`. Similar changes were made to various "Word64` primitives (which
actually worked on `Word#`. The fix is simply to apply the same wrapping
as is done for the other fixed-width primitive integers.

Addresses #3

2022-08-26 12:48 UTC, raehik commented
This builds & passes tests on at least 8.0.2 and 9.4.1 . Trivial change, more so than I expected.

2022-08-27 11:58 UTC, fumieval requested changes
Thanks, but there are build errors on GHC 9.2

2022-08-27 13:11 UTC, raehik commented
Oops. `wordToWord64#` and its inverse are new to GHC 9.4, so I define them with `id` in some slightly weirder CPP.

2022-08-27 13:57 UTC, fumieval commented
LGTM

2022-08-27 13:57 UTC, merged